// <auto-generated />
namespace Kursach_YaP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Imagees : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Imagees));
        
        string IMigrationMetadata.Id
        {
            get { return "201805230829537_Imagees"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
